import {test, expect} from '@playwright/test';
import {readFileSync} from 'node:fs';

test('Back and Forward restore section filters without persisting customer searches', async ({page}) => {
  await page.goto('/#orders');
  await page.getByRole('button', {name: 'Pending', exact: true}).click();
  await page.getByLabel('Filter orders by payment').selectOption('unpaid');
  await page.getByLabel('Sort orders').selectOption('oldest');
  await page.getByRole('searchbox').fill('Sofia');
  await expect(page.locator('tbody tr')).toHaveCount(1);
  await page.getByRole('button', {name: 'Inventory', exact: true}).click();
  await page.getByRole('button', {name: 'Low stock', exact: true}).click();
  await page.getByLabel('Sort products').selectOption('stock');
  await page.goBack();
  await expect(page.getByRole('button', {name: 'Pending', exact: true})).toHaveAttribute('aria-pressed', 'true');
  await expect(page.getByLabel('Filter orders by payment')).toHaveValue('unpaid');
  await expect(page.getByLabel('Sort orders')).toHaveValue('oldest');
  await expect(page.getByRole('searchbox')).toHaveValue('Sofia');
  await expect(page.locator('tbody tr')).toHaveCount(1);
  await expect(page.locator('#main')).toBeFocused();
  expect(await page.evaluate(() => JSON.stringify({history: history.state, local: {...localStorage}, session: {...sessionStorage}, url: location.href})) ).not.toContain('Sofia');
  await page.goForward();
  await expect(page.getByRole('button', {name: 'Low stock', exact: true})).toHaveAttribute('aria-pressed', 'true');
  await expect(page.getByLabel('Sort products')).toHaveValue('stock');
  await page.getByRole('button', {name: 'Orders', exact: true}).click();
  await expect(page.getByRole('searchbox')).toHaveValue('Sofia');
  await page.reload();
  await expect(page.getByRole('searchbox')).toHaveValue('');
  await expect(page.getByLabel('Order date scope')).toHaveValue('all');
  await page.setViewportSize({width: 1440, height: 1000});
  await page.screenshot({path: 'docs/validation/workspace-all-dates.png'});
});

test('connected order search, pagination and export reach records beyond the first page', async ({page}) => {
  const now = Date.now() / 1000;
  const makeOrder = (id, status, age) => ({id, code: `TB-${id}`, name: 'Queue customer', created_at: now - age * 86400, status, payment_status: 'unpaid', total_minor: 10000, version: 1, item_count: 1});
  const orders = [makeOrder('RECENT', 'delivered', 0), makeOrder('SECOND', 'delivered', 2), makeOrder('OLD', 'pending', 45)];
  const requests = [];
  await page.route('**/admin/workspace?*', route => {
    const params = new URL(route.request().url()).searchParams;
    requests.push(Object.fromEntries(params));
    let selected = orders;
    if (params.get('scope') === 'period' || !params.has('scope')) selected = selected.filter(o => o.created_at > now - 7 * 86400);
    if (params.get('status') === 'pending') selected = selected.filter(o => o.status === 'pending');
    if (params.get('q')) selected = selected.filter(o => `${o.name} ${o.code}`.toLowerCase().includes(params.get('q').toLowerCase()));
    const more = selected.length > 2 && !params.get('cursor');
    const rows = params.get('cursor') ? selected.slice(2) : selected.slice(0, 2);
    return route.fulfill({json: {shop_name: 'Queue shop', generated_at: now, days: 7, summary: {orders: 2, order_value: 20000, pending: 1, products: 0}, series: Array.from({length: 7}, (_, i) => ({timestamp: now - (6-i)*86400, value: 0})), orders: rows, order_total: selected.length, next_cursor: more ? 'page-two' : null, orders_truncated: more, products: [], automation: true, delivery_mode: 'dry_run', worker_age_seconds: 0, failures: 0, queue: 0}});
  });
  await page.goto('/#orders');
  await page.getByRole('button', {name: 'Connect shop', exact: true}).click();
  await page.getByLabel('Operator token', {exact: true}).fill('queue-test-token');
  await page.getByRole('button', {name: 'Connect workspace'}).click();
  await expect(page.locator('tbody tr')).toHaveCount(2);
  const download = page.waitForEvent('download');
  await page.getByRole('button', {name: 'Export CSV'}).click();
  const csv = readFileSync(await (await download).path(), 'utf8');
  expect(csv).toContain('TB-OLD');
  expect(csv.split('\r\n')).toHaveLength(4);
  await page.getByRole('button', {name: 'Load more orders'}).click();
  await expect(page.locator('tbody tr')).toHaveCount(3);
  await expect(page.getByRole('button', {name: 'Load more orders'})).toHaveCount(0);
  await page.getByRole('button', {name: 'Inventory', exact: true}).click();
  await page.goBack();
  await expect(page.locator('tbody tr')).toHaveCount(3);
  await page.getByRole('button', {name: 'Pending', exact: true}).click();
  await expect(page.locator('tbody tr')).toHaveCount(1);
  await expect(page.locator('tbody')).toContainText('TB-OLD');
  await page.getByRole('searchbox').fill('TB-OLD');
  await expect.poll(() => requests.at(-1).q).toBe('TB-OLD');
  await expect(page.locator('#main')).toHaveAttribute('aria-busy', 'false');
  expect(requests.at(-1)).toMatchObject({scope: 'all', status: 'pending', q: 'TB-OLD'});
  expect(await page.evaluate(() => JSON.stringify(history.state))).not.toContain('queue-test-token');
});
