"""Initial durable ordering schema"""

import sqlalchemy as sa
from alembic import op

revision = "0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "conversations",
        sa.Column("key", sa.String(length=150), nullable=False),
        sa.Column("psid", sa.String(length=80), nullable=False),
        sa.Column("state", sa.String(length=32), nullable=False),
        sa.Column("context", sa.JSON(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("last_customer_at", sa.Float(), nullable=False),
        sa.Column("paused", sa.Boolean(), nullable=False),
        sa.Column("rate_minute", sa.Integer(), nullable=False),
        sa.Column("rate_count", sa.Integer(), nullable=False),
        sa.Column("updated_at", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_table(
        "products",
        sa.Column("sku", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("price_minor", sa.Integer(), nullable=False),
        sa.Column("stock", sa.Integer(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("image_url", sa.Text(), nullable=False),
        sa.CheckConstraint("price_minor >= 0"),
        sa.CheckConstraint("stock >= 0"),
        sa.PrimaryKeyConstraint("sku"),
    )
    op.create_table(
        "records",
        sa.Column("key", sa.String(length=200), nullable=False),
        sa.Column("value", sa.JSON(), nullable=False),
        sa.Column("updated_at", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_table(
        "inbound_events",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("event_key", sa.String(length=200), nullable=False),
        sa.Column("conversation_key", sa.String(length=150), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("occurred_at", sa.Float(), nullable=False),
        sa.Column("received_at", sa.Float(), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("next_attempt", sa.Float(), nullable=False),
        sa.Column("error", sa.String(length=100), nullable=True),
        sa.ForeignKeyConstraint(
            ["conversation_key"],
            ["conversations.key"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("event_key"),
    )
    op.create_index(
        op.f("ix_inbound_events_conversation_key"),
        "inbound_events",
        ["conversation_key"],
        unique=False,
    )
    op.create_index(
        "ix_inbox_due", "inbound_events", ["status", "next_attempt", "id"], unique=False
    )
    op.create_table(
        "orders",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("code", sa.String(length=32), nullable=False),
        sa.Column("checkout_id", sa.String(length=36), nullable=False),
        sa.Column("conversation_key", sa.String(length=150), nullable=False),
        sa.Column("details", sa.JSON(), nullable=False),
        sa.Column("items", sa.JSON(), nullable=False),
        sa.Column("total_minor", sa.Integer(), nullable=False),
        sa.Column("shipping_minor", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("payment_status", sa.String(length=24), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("stock_released", sa.Boolean(), nullable=False),
        sa.Column("anonymized", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.Float(), nullable=False),
        sa.Column("expires_at", sa.Float(), nullable=True),
        sa.CheckConstraint("shipping_minor >= 0"),
        sa.CheckConstraint("total_minor >= 0"),
        sa.ForeignKeyConstraint(
            ["conversation_key"],
            ["conversations.key"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("checkout_id"),
        sa.UniqueConstraint("code"),
    )
    op.create_index(
        op.f("ix_orders_conversation_key"), "orders", ["conversation_key"], unique=False
    )
    op.create_table(
        "outbound_jobs",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("business_key", sa.String(length=200), nullable=False),
        sa.Column("lane", sa.String(length=200), nullable=False),
        sa.Column("destination", sa.String(length=24), nullable=False),
        sa.Column("conversation_key", sa.String(length=150), nullable=True),
        sa.Column("order_id", sa.String(length=36), nullable=True),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("next_attempt", sa.Float(), nullable=False),
        sa.Column("lease_until", sa.Float(), nullable=False),
        sa.Column("lease_token", sa.String(length=36), nullable=True),
        sa.Column("created_at", sa.Float(), nullable=False),
        sa.Column("error", sa.String(length=100), nullable=True),
        sa.ForeignKeyConstraint(
            ["conversation_key"],
            ["conversations.key"],
        ),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("business_key"),
    )
    op.create_index(op.f("ix_outbound_jobs_lane"), "outbound_jobs", ["lane"], unique=False)
    op.create_index(
        "ix_outbox_due", "outbound_jobs", ["status", "next_attempt", "id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_outbox_due", table_name="outbound_jobs")
    op.drop_index(op.f("ix_outbound_jobs_lane"), table_name="outbound_jobs")
    op.drop_table("outbound_jobs")
    op.drop_index(op.f("ix_orders_conversation_key"), table_name="orders")
    op.drop_table("orders")
    op.drop_index("ix_inbox_due", table_name="inbound_events")
    op.drop_index(op.f("ix_inbound_events_conversation_key"), table_name="inbound_events")
    op.drop_table("inbound_events")
    op.drop_table("records")
    op.drop_table("products")
    op.drop_table("conversations")
    # ### end Alembic commands ###
